backend:
  name: git-gateway
  branch: main  # Change to 'master' if your repository uses that

media_folder: "images/uploads"        # Where uploaded images are stored
public_folder: "/images/uploads"      # Public URL path for images

collections:
  - name: "news"
    label: "Trending African News"
    folder: "news-data"               # Folder where news will be stored as .md files
    create: true
    slug: "{{slug}}"                  # File name based on title slug
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
